site_name: DJUNITS version 6
site_url: https://djunits.org/
site_favicon: images/favicon.png
copyright: (c) 2015-2026 Delft University of Technology

theme:
  name: material
  navigation_depth: 1
    
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: 3
      
extra_css: 
  - css/custom.css
  
extra_javascript:
  - js/collapse_menu.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
nav:
  - Home: index.md
  - Maven use: maven_use.md
  - Package structure: package_structure.md
  - Quantity: quantity.md
  - Absolute quantity: absolute_quantity.md
  - Define quantity: define_quantity.md
  - Scale: scale.md
  - Unit System: unit_system.md
  - Unit: unit.md
  - SIQuantity: si_quantity.md
  - Vector: vector.md
  - Matrix: matrix.md
  - Quantity Table: quantity_table.md
  - Absolute Vector: absolute_vector.md
  - Absolute Matrix: absolute_matrix.md
  - Absolute Table: absolute_table.md
  - Data Storage: storage.md
  - Localization: localization.md
  - Migrating v5-v6: migration.md
  - Code generation: code_generation.md
  - Documentation v5: https://djunits.org/docs/5.4.2/manual/
  - DJUNITS documentation: https://djunits.org/docs/current/index.html
  - DJUNITS API: https://djunits.org/docs/current/apidocs/index.html
