site_name: DJUNITS
site_url: https://djunits.org/
nav:
    - Home: index.md
    - Maven use: maven_use.md
    - Package structure: package_structure.md
    - Quantities: quantities.md
theme: readthedocs
