package org.djunits.value.vfloat.scalar;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import org.djunits.unit.DurationUnit;
import org.djunits.unit.TimeUnit;
import org.djunits.unit.Unit;
import org.djunits.value.CLASSNAMES;
import org.djunits.value.base.Scalar;
import org.djunits.value.vfloat.scalar.base.FloatScalarInterface;
import org.junit.Test;

/**
 * Test the FloatScalar and FloatScalar classes for the valueOf and toString methods.
 * <p>
 * This file was generated by the djunits value test classes generator, 26 jun, 2015
 * <p>
 * Copyright (c) 2015-2022 Delft University of Technology, PO Box 5, 2600 AA, Delft, the Netherlands. All rights reserved. <br>
 * BSD-style license. See <a href="https://djunits.org/docs/license.html">DJUNITS License</a>.
 * <p>
 * @author <a href="https://www.tudelft.nl/averbraeck">Alexander Verbraeck</a>
 * @author <a href="https://www.tudelft.nl/staff/p.knoppers/">Peter Knoppers</a>
 */
public class FloatValueOfStringOfTest
{
    /**
     * Test the Duration class for the valueOf and toString methods.
     */
    @Test
    public final void durationValueOfTest()
    {
        FloatDuration duration = new FloatDuration(10.0f, DurationUnit.MINUTE);
        assertEquals("10.0000000 min", duration.toString());
        assertEquals(duration, FloatDuration.valueOf(duration.toString()));
    }

    /**
     * Test the FloatScalar and FloatScalar classes for the valueOf and toString methods.
     */
    @Test
    public final void valueOfFloatTest()
    {
        for (String className : CLASSNAMES.ALL_NODIM_LIST)
        {
            // get the class
            Class<?> scalarClass = null;
            String classPath = "org.djunits.value.vfloat.scalar.Float" + className;
            try
            {
                scalarClass = Class.forName(classPath);
            }
            catch (ClassNotFoundException exception)
            {
                fail("Class not found for Scalar class " + classPath);
            }

            // create a value so we can obtain info
            Method instantiateSIMethod = null;
            try
            {
                instantiateSIMethod = scalarClass.getMethod("instantiateSI", float.class);
            }
            catch (NoSuchMethodException | SecurityException exception)
            {
                fail("Method instantiateSI not found for Scalar class " + classPath);
            }
            Scalar<?, ?> scalarSI = null;
            try
            {
                scalarSI = (Scalar<?, ?>) instantiateSIMethod.invoke(scalarClass, Float.valueOf(10.0f));
            }
            catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException exception)
            {
                fail("Method instantiateSI failed for Scalar class " + classPath);
            }

            // get the unit
            Unit<?> unitSI = scalarSI.getDisplayUnit();

            // get the constructor
            Constructor<?> constructScalar = null;
            try
            {
                constructScalar = scalarClass.getConstructor(float.class, unitSI.getClass());
            }
            catch (NoSuchMethodException | SecurityException exception)
            {
                fail("Constructor for unit " + unitSI.getClass().getName() + " not found for Scalar class " + classPath);
            }

            // loop over all the unit types
            for (Unit<?> unit : unitSI.getQuantity().getUnitsById().values())
            {
                // FLOAT -- PREVENT UNDERFLOW / OVERFLOW
                if (unit.getScale().toStandardUnit(1.0) > 1.0E30 || 1.0 / unit.getScale().toStandardUnit(1.0) > 1.0E30)
                {
                    continue;
                }
                FloatScalarInterface<?, ?> scalar = null;
                try
                {
                    // XXX: TimeUnit of Y(1) fails. Check WHY!!!!!
                    if (unit instanceof TimeUnit)
                    {
                        continue;
                    }
                    scalar = (FloatScalarInterface<?, ?>) constructScalar.newInstance(Float.valueOf(1.0f), unit);
                    assertEquals("Float construction with unit + get in unit failed for " + unit.toString(), 1.0,
                            scalar.getInUnit(), 0.01);
                }
                catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException
                        | InstantiationException exception)
                {
                    fail("Construct with unit " + unit.getClass().getName() + " failed for Scalar class " + classPath);
                }
            }
        }
    }
}
