# This workflow will build a package using Maven and then publish it to Maven Central when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: maven-site-deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java 11 for publishing to Maven Central Repository
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install SSH keys
      run: |
        ifconfig
        echo 'install command'
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo 'private key into id_rsa'
        echo "${{ secrets.SITE_RSA_PRIVATE }}" >> ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa
        echo 'ssh-keyscan trial'
        which ssh-keyscan
        ssh-keyscan
        ssh-keyscan -H djunits.org
        echo 'ssh-keyscan to known hosts'
        ssh-keyscan -H djunits.org > ~/.ssh/known_hosts

    - name: install gpg key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Build with Maven, do not sign
      run: mvn clean package site -P release --file pom.xml
      
    - name: Make tar file of site
      run: |
        mkdir ../transfer
        tar cfz ../transfer/site.tar.gz target/site/
        cp target/*.jar ../transfer
        tar cfz ../transfer/docs.tar.gz docs/
        cp pom.xml ../transfer
        cp .flattened-pom.xml ../transfer/flattened-pom.xml
        rsync -avz ../transfer/* djunits@djunits.org:/data/home/web/djunits.org/new
